# Generated by Django 5.2.8 on 2025-11-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_address', models.CharField(max_length=255)),
                ('arrival_city', models.CharField(max_length=100)),
                ('arrival_address', models.CharField(max_length=255)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('available_seats', models.PositiveIntegerField()),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='active', max_length=20)),
                ('luggage_size', models.CharField(default='Moyen', max_length=50)),
                ('accepts_pets', models.BooleanField(default=False)),
                ('accepts_smoking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-departure_date', '-departure_time'],
            },
        ),
    ]
