# Generated by Django 4.2.7 on 2025-11-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='transport_type',
            field=models.CharField(choices=[('car', 'Voiture'), ('bus', 'Bus'), ('train', 'Train'), ('van', 'Van/Minibus')], default='car', max_length=20),
        ),
    ]
