# Generated by Django 4.2.7 on 2025-12-22 21:23

import apps.trips.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(validators=[apps.trips.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
