# Generated by Django 4.2.7 on 2025-12-22 21:49

import apps.trips.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0004_alter_trip_available_seats_alter_trip_departure_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_address', models.CharField(max_length=255)),
                ('arrival_city', models.CharField(max_length=100)),
                ('arrival_address', models.CharField(max_length=255)),
                ('departure_time', models.TimeField()),
                ('available_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire')], max_length=20)),
                ('start_date', models.DateField(validators=[apps.trips.models.validate_future_date])),
                ('end_date', models.DateField()),
                ('days_of_week', models.CharField(blank=True, help_text='0=Lun, 1=Mar, ..., 6=Dim. Séparez par des virgules.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='recurring_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='trips.recurringtrip'),
        ),
    ]
