# Generated by Django 4.2.7 on 2025-12-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_recurringtrip_trip_recurring_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtrip',
            name='arrival_address',
            field=models.CharField(max_length=255, verbose_name="Adresse d'arrivée"),
        ),
        migrations.AlterField(
            model_name='recurringtrip',
            name='arrival_city',
            field=models.CharField(choices=[('tunis', 'Tunis'), ('ariana', 'Ariana'), ('ben_arous', 'Ben Arous'), ('manouba', 'Manouba'), ('nabeul', 'Nabeul'), ('zaghouan', 'Zaghouan'), ('bizerte', 'Bizerte'), ('beja', 'Béja'), ('jendouba', 'Jendouba'), ('kef', 'Le Kef'), ('siliana', 'Siliana'), ('kairouan', 'Kairouan'), ('kasserine', 'Kasserine'), ('sidi_bouzid', 'Sidi Bouzid'), ('sousse', 'Sousse'), ('monastir', 'Monastir'), ('mahdia', 'Mahdia'), ('sfax', 'Sfax'), ('gabes', 'Gabès'), ('medenine', 'Médenine'), ('tataouine', 'Tataouine'), ('gafsa', 'Gafsa'), ('tozeur', 'Tozeur'), ('kebili', 'Kébili')], max_length=100, verbose_name="Gouvernorat d'arrivée"),
        ),
        migrations.AlterField(
            model_name='recurringtrip',
            name='departure_address',
            field=models.CharField(max_length=255, verbose_name='Adresse de départ'),
        ),
        migrations.AlterField(
            model_name='recurringtrip',
            name='departure_city',
            field=models.CharField(choices=[('tunis', 'Tunis'), ('ariana', 'Ariana'), ('ben_arous', 'Ben Arous'), ('manouba', 'Manouba'), ('nabeul', 'Nabeul'), ('zaghouan', 'Zaghouan'), ('bizerte', 'Bizerte'), ('beja', 'Béja'), ('jendouba', 'Jendouba'), ('kef', 'Le Kef'), ('siliana', 'Siliana'), ('kairouan', 'Kairouan'), ('kasserine', 'Kasserine'), ('sidi_bouzid', 'Sidi Bouzid'), ('sousse', 'Sousse'), ('monastir', 'Monastir'), ('mahdia', 'Mahdia'), ('sfax', 'Sfax'), ('gabes', 'Gabès'), ('medenine', 'Médenine'), ('tataouine', 'Tataouine'), ('gafsa', 'Gafsa'), ('tozeur', 'Tozeur'), ('kebili', 'Kébili')], max_length=100, verbose_name='Gouvernorat de départ'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival_address',
            field=models.CharField(max_length=255, verbose_name="Adresse d'arrivée"),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival_city',
            field=models.CharField(choices=[('tunis', 'Tunis'), ('ariana', 'Ariana'), ('ben_arous', 'Ben Arous'), ('manouba', 'Manouba'), ('nabeul', 'Nabeul'), ('zaghouan', 'Zaghouan'), ('bizerte', 'Bizerte'), ('beja', 'Béja'), ('jendouba', 'Jendouba'), ('kef', 'Le Kef'), ('siliana', 'Siliana'), ('kairouan', 'Kairouan'), ('kasserine', 'Kasserine'), ('sidi_bouzid', 'Sidi Bouzid'), ('sousse', 'Sousse'), ('monastir', 'Monastir'), ('mahdia', 'Mahdia'), ('sfax', 'Sfax'), ('gabes', 'Gabès'), ('medenine', 'Médenine'), ('tataouine', 'Tataouine'), ('gafsa', 'Gafsa'), ('tozeur', 'Tozeur'), ('kebili', 'Kébili')], max_length=100, verbose_name="Gouvernorat d'arrivée"),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_address',
            field=models.CharField(max_length=255, verbose_name='Adresse de départ'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_city',
            field=models.CharField(choices=[('tunis', 'Tunis'), ('ariana', 'Ariana'), ('ben_arous', 'Ben Arous'), ('manouba', 'Manouba'), ('nabeul', 'Nabeul'), ('zaghouan', 'Zaghouan'), ('bizerte', 'Bizerte'), ('beja', 'Béja'), ('jendouba', 'Jendouba'), ('kef', 'Le Kef'), ('siliana', 'Siliana'), ('kairouan', 'Kairouan'), ('kasserine', 'Kasserine'), ('sidi_bouzid', 'Sidi Bouzid'), ('sousse', 'Sousse'), ('monastir', 'Monastir'), ('mahdia', 'Mahdia'), ('sfax', 'Sfax'), ('gabes', 'Gabès'), ('medenine', 'Médenine'), ('tataouine', 'Tataouine'), ('gafsa', 'Gafsa'), ('tozeur', 'Tozeur'), ('kebili', 'Kébili')], max_length=100, verbose_name='Gouvernorat de départ'),
        ),
    ]
