# Generated by Django 4.2.27 on 2025-12-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_recurringtrip_arrival_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtrip',
            name='country',
            field=models.CharField(default='Tunisie', max_length=50, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(default='Tunisie', max_length=50, verbose_name='Pays'),
        ),
    ]
