# Generated by Django 4.2.27 on 2025-12-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_recurringtrip_arrival_lat_recurringtrip_arrival_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtrip',
            name='accepts_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringtrip',
            name='accepts_smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringtrip',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recurringtrip',
            name='luggage_size',
            field=models.CharField(default='Moyen', max_length=50),
        ),
        migrations.AddField(
            model_name='recurringtrip',
            name='transport_type',
            field=models.CharField(choices=[('car', 'Voiture'), ('bus', 'Bus'), ('train', 'Train'), ('van', 'Van/Minibus')], default='car', max_length=20),
        ),
    ]
