# Generated by Django 4.2.27 on 2026-01-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_recurringtrip_accepts_pets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='arrival_lat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='arrival_lng',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='departure_lat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='departure_lng',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='recurring_pattern',
        ),
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.DeleteModel(
            name='RecurringTrip',
        ),
    ]
