# Generated by Django 4.2.7 on 2025-12-22 21:23

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[apps.users.models.validate_past_date]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+99999999'. De 8 à 15 chiffres autorisés.", regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
