# Generated by Django 4.2.7 on 2025-12-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_of_birth_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_document',
            field=models.ImageField(blank=True, null=True, upload_to='identity_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_document_type',
            field=models.CharField(blank=True, choices=[('id_card', "Carte d'identité"), ('passport', 'Passeport'), ('driving_license', 'Permis de conduire')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Non vérifié'), ('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='unverified', max_length=20),
        ),
    ]
